### ISSUE TITLE
discussion: remove pos from (Abstract)Type

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#1084]
I think the position of a Type is too ambiguous to give satisfying information. IMHO a type can have anything from zero to a lot of positions. 

In many cases what we actually want is the position of the feature defining the type. Then there is types which are generic parameters, so I think we should add `pos` to `Generic`.

As can be seen in #1082 there is 'only' two failing tests if the type always reports the position of the feature if available and otherwise returns that no position is available.

**Comment by fridis** [comment]
I would be happy if you went through all places that use `AbstractType.pos` and replaced them by something better such that `AbstractType.pos` can be removed.
