### ISSUE TITLE
type parameter name conflict

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#1089]
```
ex_name_conflict is
  has_identity(T type) is
    e T is abstract

  has_zero(redef T type : has_zero T) : has_zeros T is
    type.zero has_zero.this.type is abstract

  has_zeros(T type : has_zero T) is
    something : has_identity T is
      redef e T is T.zero
```
causes this error
```
ex_name_conflict.fz:10:22: error 1: Could not find called feature
      redef e T is T.zero
---------------------^
Feature not found: 'zero' (no arguments)
Target feature: 'Any.type'
In call: 'deref(e.this.#^ex_name_conflict.has_zeros.something.e).T.zero'

one error.
```

In `T.zero`, `T` now seems to refer to the `T` from `has_identity` without constraints, not the `T` with constraints from `has_zeros`. Indeed, the error disappears when changing the type parameter name of `has_identity` from `T` to something else, like `V`.

**Comment by fridis** [comment]
This is a general problem related to handling of  ambiguity between inherited and outer features. Currently, Fuzion prefers inherited over outer features, as can be seen in this small example: 
```
 > cat ex1089a.fz 
ex1089a is
  a is
    x => say "a.x"

  b is
    x => say "b.x"

  c : b is
    d : a => x  # this will prefer the inherited 'a.x' over the outer 'b.x'

  c.d
 > ./build/bin/fz ex1089a.fz 
a.x
```
Possible solutions
- produce an error in this case and require being explicit, e.g., `c.this.x` or `d.this.x`
- require renaming when inheriting

**Comment by fridis** [comment]
Here is a  fix for the original example using `has_zeros.this.T` to be explicit:
```
ex_name_conflict is
  has_identity(T type) is
    e T is abstract

  has_zero(redef T type : has_zero T) : has_zeros T is
    type.zero has_zero.this.type is abstract

  has_zeros(T type : has_zero T) is
    something : has_identity T is
      redef e T is has_zeros.this.T.zero
```
