### ISSUE TITLE
type inference: infer generic of outer via usage of inner

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#1097]
`group` would could be called without explicit type when inferring of T by usage in inner features would be none ambigous:
```
ex =>
  group(T type) is
    a (b T) is
    c (d T) is

  group.a 2
```

**Comment by fridis** [comment]
Is this the same as #340?

**Comment by michaellilltokiwa** [comment]
duplicate, see #340
