### ISSUE TITLE
Better syntax sugar for lazy evaluation

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#1166]
Recent PRs (#1163, #1150)  have shown the need for a simple syntax for lazy evaluation to avoid duplication of features (lazy and non-lazy variants). Need to add a design page at flang.dev to compare possible approaches and decide on one solution.

**Comment by fridis** [comment]
I have added a page to [flang.dev](https://flang.dev/design/lazy_args) that lists approaches in other languages and shows different possibilities.

**Comment by michaellilltokiwa** [comment]
The `lazy feature` approach sounds really good. Only thing where I'm not having a clear picture yet are all the downsides of being implicit at use and implicit at call.

**Comment by fridis** [comment]
> The `lazy feature` approach sounds really good. Only thing where I'm not having a clear picture yet are all the downsides of being implicit at use and implicit at call.

Being implicit is always both: a pro since it is less typing and a cons since it does some hidden magic that might cause confusion.
