### ISSUE TITLE
Add `ref v` expression

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#1219]
See #341 for an example where this is useful. 
This would enhance the duality of types and expressions, so `ref T` is the reference type to a value of type `T` while `ref v` is a reference to a copy of the value `v`.

**Comment by fridis** [comment]
I am no longer sure whether I really want this...

**Comment by michaellilltokiwa** [comment]
@fridis can this be closed?

**Comment by fridis** [comment]
Since types `ref t` no longer exist, we also do not need expressions `ref v`. Closing this issue.
