### ISSUE TITLE
Support for text blocks

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#1249]
Fuzion String literals are currently limited to a single line. Would be nice to have support for multi-line text blocks. Java introduced nice support for text blocks in [JEP 378](https://openjdk.org/jeps/378). We might want to provide something similar, but with support for string templates `"$sum = {a+b}"`.

**Comment by michaellilltokiwa** [comment]
In the JEP:
> Trailing white space is most often unintentional, idiosyncratic, and insignificant. It is overwhelmingly likely that the developer does not care about it. Trailing white space characters are similar to line terminators, in that both are invisible artifacts of the source code editing environment. With no visual guide to the presence of trailing white space characters, including them in the content would be a recurring source of surprise, as it would affect the length, hash code, etc, of the string.

@tokiwa-software/developers Do you agree? Should we do this as well?

**Comment by fridis** [comment]
I do agree. Might even go further and consider trailing white space an error. If trailing white space is desired, `\s` must be used (and we should support it as well!).
