### ISSUE TITLE
Allow loop-defined features to be qualified?

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#1444]
```
To solve this, you may qualify the feature using 'ryu_test.#loop2.this.num' or 'universe.this.num'.
```

It is in fact not possible to solve this at the moment, even if you could type out `#loop2` the counter suffix to loop is not guaranteed to stay constant for multiple invocations of Fuzion. Would it be worth to have a special feature `this_loop.num` or similar?

**Comment by fridis** [comment]
Please do not create out-of-contexts issues. What did you do to create this message? What code did you run?

**Comment by michaellilltokiwa** [comment]
@maxteufel Can you provide some example code here that produces a similar error message?

**Comment by michaellilltokiwa** [comment]
I think this should select just loops `num`. Not sure why it does not. If user wants to call `universe.num` one would have to use full qualifier.

**Comment by michaellilltokiwa** [comment]
duplicate of #2347
