### ISSUE TITLE
Language improvement: Syntax sugar for creating dictionaries / maps / etc.

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#148]
Initialization of a map as in [idiom 244](https://flang.dev/idioms/idiom244) is ugly
```
 m := mapOf ["lundi", "mardi", "mercredi"] ["月曜日", "火曜日", "水曜日" ]
```
should be something like
```
 m := [ "lundi" => "月曜日"
        "mardi" => "火曜日"
        "mercredi" => "水曜日" ]
```

**Comment by michaellilltokiwa** [comment]
there now is also this, which I think is good enough:
```
  m := mapOf [("lundi", "月曜日"), ("mardi", "火曜日"), ("mercredi", "水曜日")]
```
or
```
  m := mapOf [ ("lundi", "月曜日"),
               ("mardi", "火曜日"),
               ("mercredi", "水曜日") ]
```
what do you think? @fridis @maxteufel @WaelYoussfi

**Comment by WaelYoussfi** [comment]
> there now is also this, which I think is good enough:
> ```
>   m := mapOf [("lundi", "月曜日"), ("mardi", "火曜日"), ("mercredi", "水曜日")]
> ```
> or
> ```
>   m := mapOf [ ("lundi", "月曜日"),
>                ("mardi", "火曜日"),
>                ("mercredi", "水曜日") ]
> ```
> what do you think? @fridis @maxteufel @WaelYoussfi 

Looks good to me.

**Comment by fridis** [comment]
@michaellilltokiwa: probably the best compromise between convenient syntax and not adding syntax sugar. Please close this issue.
