### ISSUE TITLE
Possibility to omit unneeded type parameters

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#1489]
Sometimes it makes sense to define type features that do not make use of all type parameters of its outer feature. (see #1488 transducers.type.filter for where I came to this conclusion.)
It would be nice if we did not need to specify type parameters that are subsequently unused.
Example:
```
ex is
  a(A,B type) is
    type.some_type_feature(arg A) unit is


  (a i32).type.some_type_feature 3
```

**Comment by fridis** [comment]
`void` could be used for this. I would not go so far and completely omit the missing ones, since then there would be no way in your example to omit `A`.
How about using `_` for some variant of `void`, then you could do 
```
(a i32 _).type.some_type feature 3
```

**Comment by michaellilltokiwa** [comment]
This is now possible
