### ISSUE TITLE
Do not require `.type` when `feat.this` is used as type

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#1570]
consider this example:
```
type.zero numeric.this.type is abstract
```
this could be:
```
type.zero numeric.this is abstract
```
since it is clear that numeric.this is used as type. the `.type` is kind of redundant here?

Of course this applies only when a feature is used as type. Calls would still need `.this.type`:
```
wrapping_integer.this.type.max.thiz
```

**Comment by fridis** [comment]
Yes, this is may plan anyways. Even more, I would like to change the grammar such that the rule for `actual`
```
actual   : expr | type;
```
could be removed and `expr` could be used instead.
