### ISSUE TITLE
What if we dropped the need for `.type` in calls?

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#1571]
If same name for features and type features would be forbidden the `.type` in calls would be unnecessary.

This is currently allowed but maybe it makes sense to forbid this?
```
ex is

  a is

  type.a is

  say a
  say ex.type.a
```

Then we could do this:

```
ex is
  type.a is

  say a        # ex.this.type.a
  say ex.a   # ex.type.a
```

This would make it less clear that `ex.a` does not call `ex` but I wonder if that would actually be a problem?

**Comment by fridis** [comment]
This is a good suggestion that fits well with my plan to unify values and types further anyway. `.type` in general should be required only when it would otherwise be unclear if a value or type is meant. An example would be `xyz.this.type` that, in most situations, could be just `xyz.this`.
