### ISSUE TITLE
Allow renaming of inherited type parameters

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#1614]
This example exibits the problem. It is not possible currently to inherit from a and b because they use the same identifier `T`.
```
ex =>
  a (T type) is
  b (T type) is
  c (U type): a U, b U is
    say T.name
```

```
test.fz:4:3: error 1: Repeated inheritance of conflicting features
  c (U type): a U, b U is
--^
Feature 'ex.c' inherits feature 'T' (no arguments) repeatedly: 'ex.a.T' defined at /home/sam/playground/test.fz:2:6:
  a (T type) is
-----^
and 'ex.b.T' defined at /home/sam/playground/test.fz:3:6:
  b (T type) is
-----^
To solve this, you could add a redefinition of 'T' to 'ex.c'.

one error.
```

**Comment by fridis** [comment]
This is a general issue, it should be possible to rename any inherited feature, not only type parameters. This solves some other issues

- in a redefinition, you could call the original feature (by inheriting it repeatedly, while one version is redefined while the other is renamed)
- it would allow some fancy repeated inheritance, e.g., `ring` could inherit from `monoid` twice, modelling the additive and multiplicative monoids that form the ring. 
- Betrand Meyer's [Object-Oriented Software Construction](https://en.wikipedia.org/wiki/Object-Oriented_Software_Construction) has more examples. 

My plan is to have a rename clause as part of the inherits clause and extend `AbstractFeature.handDown` to do the renaming.

**Comment by michaellilltokiwa** [comment]
not applicable anymore
