### ISSUE TITLE
`Expr.toString()` should not be used in comiler error messages

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#1670]
Currently, `Expr.toString()` attempts to re-construct the source code, but this is doomed to fail since loads of information (where to place parentheses, white space, etc.) is lost and added (e.g., following outer references to find the correct outer instance). This results in ugly and strange error messages.  In particular, if the expression was generated artificially for syntax sugar like lambdas or lazy arguments, this gets fully confusing. 

Instead, wherever an expression is presented in an error message, it should best be taken from the source code directly. One way to do this would be to record the start and the end position of an expression and extract the exact source code when creating the error. It might make sense to not replace the `SourcePosition` given by `Expr.pos()`, by a `SourceSection` that might be stored by the user of the expression.

Here is an example:

```
expr is

  a is
    b is
      c =>
        s String := ((( xyz + 123 )))

  xyz := 456

  a.b.c
```
that produces

```
 > ./build/bin/fz expr.fz 

/home/fridi/fuzion/clean/fuzion.1/expr.fz:6:9: error 1: Incompatible types in assignment
        s String := ((( xyz + 123 )))
--------^
assignment to field : 'expr.a.b.c.s'
expected formal type: 'String'
actual type found   : 'ref i32'
assignable to       : 'Any',
                      'ref equatable',
                      'ref has_hash',
                      'ref has_interval',
                      'ref has_partial_order',
                      'ref has_total_order',
                      'ref i32',
                      'ref integer',
                      'ref numeric',
                      'ref wrapping_integer'
for value assigned  : 
{
  {
    {
      box(deref(deref(deref(c.this.#^expr.a.b.c).#^expr.a.b).#^expr.a).xyz.infix + 123)
    }
  }
}

To solve this, you could change the type of the target 'expr.a.b.c.s' to 'ref i32' or convert the type of the assigned value to 'String'.

one error.
```
In particular, the `for value assigned` section is bad, should maybe be
```
for value assigned  : ((( xyz + 123 )))
```
or even
```
for value assigned  : /home/fridi/fuzion/clean/fuzion.1/expr.fz:6:9: error 1: Incompatible types in assignment
        s String := ((( xyz + 123 )))
--------------------^^^^^^^^^^^^^^^^^
```
or using even nicer ASCII-graphics with ANSI colors to highlight the code.

**Comment by michaellilltokiwa** [comment]
@fridis Are we sure that expr.ToString() happens only for code not loaded from fum-files? If not, we may have to persist the source code in the fum-files?

**Comment by fridis** [comment]
> @fridis Are we sure that expr.ToString() happens only for code not loaded from fum-files? If not, we may have to persist the source code in the fum-files?

nor sure about this. I would not add this to the fum files, probably would not add this information to Expr at all, but instead check all locations that use Expr.toString() in an error message and make the required information is available there (e.g., a `Call` could store the source code section of its actual arguments). An `Expr` may not come from source code if it is generated as part of syntax sugar.
