### ISSUE TITLE
private visibility in public type should allow private value arguments

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#1860]
I ran into this in #1859 : making `fuzion.sys.Pointer` private causes an error when compiling `fuzion.sys.internal_array` since this type is used as an value argument to that constructor. However, it should be sufficient for a public type to have all its type parameter's constraints public as well, while the value argument types might well have their visbility as restricted as the feature.

**Comment by michaellilltokiwa** [comment]
Hmm, I think this could lead to unexpected behavior. Because then every type defined is sometimes usable/visible, sometimes not? Why not just mark `Pointer` as `private:module`? I tried this and it works.

**Comment by fridis** [comment]
> Hmm, I think this could lead to unexpected behavior. Because then every type defined is sometimes usable/visible, sometimes not? Why not just mark `Pointer` as `private:module`? I tried this and it works.

I probably use `private` when I should have used `module`, I will check this again.
