### ISSUE TITLE
`hash` should be a type feature

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#2000]
This is related to #606 and #1999:

Just like equality, the `hashable.hash` should be a type feature and not be defined for Any and inherited.

For `hashable.hash` to be useful, the following invariant should hold:
```
  (T.hash a != T.hash b) || T.equality a b
```
So the semantics of `hash` depends on `type.equality`, so `hash` should be a type feature as well.

This also means that `hash` cannot be an inner feature that is inherited, but maybe a prefix or postfix operand if we find a suitable one (`#` is already used for comments, though...).

**Comment by michaellilltokiwa** [comment]
> If both were required, `hash` equality would be equivalent to regular equality, but that is not the purpose of hashes. I believe a good hash satisfies the condition `(a = b) : (hash a = hash b)` (if you take the hash of the same element, you get the same hash, but not (necessarily) your condition proposed above.

A function always returning e.g. 1 would qualify as a hash function under this definition, right?

Also hash functions need to be deterministic, so this needs to hold as well, I think:
`(hash a != hash b) : (a != b)`

**Comment by fridis** [comment]
> A function always returning e.g. 1 would qualify as a hash function under this definition, right?

yes, but one with 0 entropy, so pretty useless.

> Also hash functions need to be deterministic, so this needs to hold as well, I think: `(hash a != hash b) : (a != b)`

no, this does, e.g., not hold for the constants hash function `1`. This only holds for a _perfect_ hash function.

**Comment by fridis** [comment]
> We can do a bit of math on your invariant and get the following equivalence:
> 
> ```
>   (T.hash a != T.hash b) || T.equality a b # insert definition of !=
>   !(T.hash a = T.hash b) || T.equality a b # well-known equivalence
>   (T.hash a = T.hash b) : T.equality a b
> ```
> 
> Now, the existing `hashable` postulates:
> 
> https://github.com/tokiwa-software/fuzion/blob/cafd46eaf2b219f116b30a7ccea166539e5340b5/lib/property/hashable.fz#L33-L35
> 
> (note that the second condition here is equivalent to the first one because it is well known that `a : b` and `!b : !a` are equivalent (contraposition))
> This would be the exact opposite implication of your postulate in the comment above.
> 
> If both were required, `hash` equality would be equivalent to regular equality, but that is not the purpose of hashes. I believe a good hash satisfies the condition `(a = b) : (hash a = hash b)` (if you take the hash of the same element, you get the same hash, but not (necessarily) your condition proposed above.

I was wrong, it has to be the other way around.
