### ISSUE TITLE
inspectCode/markUsed must separately handle code of precondition and code of feature

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#2084]
from #2009:
> One detail that should be fixed, maybe in a separate PR: the precondition should not be part of the code of a feature like the postcondition is. Instead. the precondition is part of a call to a feature. This becomes important, e.g., when there is a precondition of an abstract feature: This is precondition will be executed on a call to that abstract feature, while the call will end up in a redefinition that might have a different (weaker) precondition (while Fuzion currently does not enforce that preconditions are weakened and postconditions are strengthened in redefinitions).

**Comment by fridis** [comment]
This is fixed with #3260.
