### ISSUE TITLE
C backend: potential overflow in nano_time intrinsic

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#223]
The code
```
          return CExpr.call("clock", new List<>())
            .mul(CExpr.uint64const(1_000_000_000))
            .div(CExpr.ident("CLOCKS_PER_SEC"))
            .ret();
```
may result in an overflow, see the documentatrion of clock:

_The C standard allows for arbitrary values at the start of the program; subtract the value returned from a call to clock() at the start of  the program to get maximum portability._

Fairly unlikely, but awful if it happens...

**Comment by michaellilltokiwa** [comment]
Code has meanwhile been changed.
