### ISSUE TITLE
AoC issue: codepoint literals

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#2320]
This is inspired by the 1 Dec AdventOfCode puzzle: 
The code to get the unicode value from a single constant character is somewhat clumsy: 
```
  v := "0".as_codepoints.first.val
```
It might be nice to have codepoint literals similar to String literals, one possibility would be to use `' ` like a `char` constants in Java:
```
  v := '0'.val
```
An alternative would be to treat string literals that can be encoded as a single codepoint as a codepoint constant, but this would have the strange effect that `"I"` and `"you"` would have different types.

**Comment by michaellilltokiwa** [comment]
Something like this makes it less clumsy even today:
```
ex is

  String.val => String.this.as_codepoints.first.val

  say "A".val
  say "a".val
```
```
65
97
```

**Comment by michaellilltokiwa** [comment]
@maxteufel I'm not sure if "a" being of type `codepoint` is a good idea but it should be noted that in a lot of occasions this will just work since codepoint inherits from `String`. So these types have some kind of compatibility.
