### ISSUE TITLE
AoC issue: CFG Analysis runs into very deep recursion 

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#2322]
Found this during Dec 7 AoC performance analysis, but a simple HelloWorld is enough
```
> ./build/bin/fz -XjavaProf build/tests/hello/HelloWorld.fz 
```
This results in the attached flame graph with deep recursion. 
![pid48588-fuzion-XjavaProf-flamegraph](https://github.com/tokiwa-software/fuzion/assets/48821596/6062a000-6ba9-45cf-a9e8-020a7f523bcf)

**Comment by michaellilltokiwa** [comment]
CFG is not used anymore, but keeping open

**Comment by michaellilltokiwa** [comment]
closing this, not relevant anymore
