### ISSUE TITLE
type features taking only outer feature as argument, could be used as instance method with no args

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#2362]
example:
```
float is
   public type.sqrt (val float.this) => square_root val
```
currently has to be used like this:
```
f64.type.sqrt 5.5
```
would be nice if this would work as well
```
(5.5).sqrt
```

**Comment by fridis** [comment]
Well, why is this a type feature in the first place? I think this has historic reasons (used to be defined in `f64s`, so just moving this to `f64` or `float` might do the trick!

Adding a feature `prefix_math` that defines things like `sqrt(T type: float, v T) => v.sqrt` could then be used in inherits clause if one wants to write `sqrt 5.5`.
