### ISSUE TITLE
AoC issue: need mutable versions of  `array2`, `array3`

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#2379]
Like in [Day 16](https://github.com/fridis/fuzion_aoc/blob/main/2023/16/part2.fz), a 2D mutable array would be good.

**Comment by Nimux2** [comment]
I am currently working on this.

**Comment by michaellilltokiwa** [comment]
fixed in https://github.com/tokiwa-software/fuzion/pull/6985
