### ISSUE TITLE
Always use (in-memory) `.fum` file as input for middle end

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#2411]
I thought I had done this change before, but just found that that is apparently not true: When the middle end creates clazzes from the features created by the front end, the AST with all the complexity from the parser and front end should no longer be used. 
In particular, it is awful to have a dependency from `dev.flang.air.Clazz` to `dev.flang.ast.SrcModule`.

**Comment by michaellilltokiwa** [comment]
implemented in #2817
