### ISSUE TITLE
type parameter inference for actual argument outer.this should be `ref outer.type`

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#254]
`outer.this` could be any heir feature of `outer`, so it might be a reference or a value type.  An assignment to an argument of this type hence requires the argument to be a ref type. 

Currently, this situation causes an error requiring a workaround as in `psSet.addAll`

```
  addAll (s Sequence<K>) ref psSet<K> is 
    this_ref ref psSet<K> := psSet.this
    s.reduce this_ref ((r,k) -> r.add k)
```
With type inference turning `psSet.this` into a `ref`, this could be
```
  addAll (s Sequence<K>) ref psSet<K> is 
    s.reduce psSet.this ((r,k) -> r.add k)
```

**Comment by michaellilltokiwa** [comment]
not relevant anymore, since: #1705
