### ISSUE TITLE
pre-Condition in c-backend not always evaluated

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#270]
This example runs fine when using c-backend but should fail:
```
ex
  pre false
  =>
  say "hello"
```

the same problem occurs when applying this patch:

```patch
diff --git a/lib/stream.fz b/lib/stream.fz
index 28b11e67..ef74b2bd 100644
--- a/lib/stream.fz
+++ b/lib/stream.fz
@@ -39,7 +39,10 @@ stream(redef T type) ref : Sequence<T> is
         ref : Cons<T,list<T>>
           memoizedTail option<some<list<T>>> := nil
           head => h
-          tail =>
+          tail
+            pre false
+            =>
+            say "tail"
             if !memoizedTail.exists
               set memoizedTail := some fromStream
             memoizedTail.get.val
```
example test-code for the diff above:
```
ex
  =>
  say [1,2,3,4,5,6,7].asStream.take 2
```

**Comment by fridis** [comment]
The first case is a bug in the C backend, it was just forgotten to check the pre-condition of the main feature (or require that pre-condition to be empty or something). 

The second case is a bug in the interpreter: On a call to tail. the caller has to respect the precondition of the static type of the call target, i.e., `Cons.tail` in this case. The precondition of a redefinition can only be relaxed (which is not supported yet:-), so `pre false` should not be allowed but something like `pre else false` meaning that if the redefined feature's (Cons.tail)  precondition fails, we can relax it (while `false` would just leave it the same). This is done correctly in compiled code, the interpreter, however, checks the precondition of the redefinition, which it should not and which causes the failure now. 

The important thing that is missing for all backends is support for redefined pre- and postconditions.
