### ISSUE TITLE
Poor error message for not installed effect

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#2722]
This error:
```
 > ./build/bin/fz -e "lm : mutate is {}; _ := lm.env"

error 1: Used effect `lm` never instantiated.

one error.
```
is wrong (the problem is that the effect is not installed in this context, it may well be instantiated and installed in other contexts) and missing any context like a source code position or, better, a call trace leading to the problem.

**Comment by michaellilltokiwa** [comment]
partial fix:  #2730
