### ISSUE TITLE
`effect.abortable(T,f)` instrinsic should support functions `f` with non-unit-type results

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#2728]
In `effect.run`, `simple_effect.use` and `simple_effect.go`, the function argument is currently wrapped into an instance of `Effect_Call` just because I was too lazy to support arbitrary result types in all backends for this intrinsics. Would be nicer to avoid this extra wrapping.

**Comment by michaellilltokiwa** [comment]
This is not relevant anymore since the implementation of effects changed in the meantime.
