### ISSUE TITLE
misleading syntax error when declaring a routine using the old curly braces syntax

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#2773]
got this failure in a local flang.dev test run:
```
SKIP RUNNING content/tutorial_using_braces/examples/voidType.fz, type checking content/tutorial_using_braces/examples/voidType.fz: FAILED
```
the example is:
```
endless void {
  do {
    yak "∞";
  }
}

res void := endless;
```
Jenkins can't detect issues since it skips this test to avoid an endless loop.

An example that terminates and fails with the same error:
```
endful unit {
  for i in 0..10 do {
    say i;
  }
}
```

**Comment by fridis** [comment]
This is intended, the test needs to be changed to include `=>` before the `{`. The reason is that I had recently removed the special handling for feature declarations using braces from the parser to simplify the grammar. The result is that for a routine, `=>` or `is` is always required.
