### ISSUE TITLE
`8 %% 5 = 3` does not cause an error, but I think it should 

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#3036]
I am very confused right now: the following line `8 % 5 = 3` behaves correctly:
```
 > ./build/bin/fz -e "say (8 % 5 = 3)"
true
```
However, suing `%%` instead should result in a`bool` and produce an error if used in `8 %% 5 = 3`, but it does not:
```
 > ./build/bin/fz -e "say (8 %% 5 = 3)"
false
```
Placing parentheses as in `(8 %% 5) = 3` or  `8 %% (5 = 3)` produces an error as expected.

**Comment by michaellilltokiwa** [comment]
Funny example. This is considered to be a chained boolean expression. Maybe we should be more restrictive than current logic of what we consider to chained booleans:
```java
    if (Types.resolved != null &&
        targetFeature(res, thiz) == Types.resolved.f_bool &&
        isInfixOperator() &&
        target() instanceof ParsedCall pc &&
        pc.isInfixOperator() &&
        pc.isOperatorCall(false))
```

**Comment by michaellilltokiwa** [comment]
What if chained boolean expression are only possible with those special operators?: <,>,≤,≥,=,<=,>=

@tokiwa-software/developers: opinions?

**Comment by fridis** [comment]
> What if chained boolean expression are only possible with those special operators?: <,>,≤,≥,=,<=,>=
> 
> @tokiwa-software/developers: opinions?

Yes, we need this restriction! Maybe include `infix !=` as well.
