### ISSUE TITLE
matchCaseTags returns empty result

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#304]
This example triggers the post condition of #303

```
ex =>

  e is

    b is

    l choice<i32,b> := b

    d(c ref e) is
      match c.l
        aa i32 => say aa
        bb b => say bb

    call =>
      d e.this

  e.call
```
this works (`e ref is` instead of `e is`): 
```
ex =>

  e ref is

    b is

    l choice<i32,b> := b

    d(c ref e) is
      match c.l
        aa i32 => say aa
        bb b => say bb

    call =>
      d e.this

  e.call
```

I assigned label `bug: frontend` because I think the issue is that there are two types created for l:
`(ref e).l` and `e.l`  which is an issue becuase i.e. `isAssignableFrom` returns false in this case.

**Comment by fridis** [comment]
Here is another example using an inner type as a type parameter and then mixing it up with value and ref outer types:
```
 > cat ex304b.fz 
mr m is om          # om get boxed to 'ref om' with static type 'm'
mr.x

om : m is
  entry is
    i := 42
  s := sa entry      # sa.T is om.entry
  x => s.f e->e.i    # when called via mr.x, type is '(ref om).x', type of 'e' is '(ref om).entry'

m ref is
  x unit is abstract

sa(T type, v T) is
  f(f T -> i32) unit is _ := f v  # v's type is 'om.entry', f expected 'ref om.entry'.
```
which produces:
```
 > ./build/bin/fz -c -Xdfa=on ex304b.fz 

error 1: NYI: in ref om.x.ref #fun0.call no targets for Call to ref om.entry.i target om.entry

one error.

```

**Comment by michaellilltokiwa** [comment]
@fridis I think this can be closed since these examples now produce errors in frontend:
- Call performed on a boxed (explicit 'ref') type not permitted here.
- Call has an ambiguous result type since target of the call is a 'ref' type.
