### ISSUE TITLE
spawned threads keep application alive when using interpreter, not when using c-backend, should unify behaviour

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#307]
```
ex =>

  concur.thread.spawn (() ->
    say "hello"
    )
```
With c-backend there is no error but nothing is printed to stdout, interpreter prints hello as expected.

**Comment by fridis** [comment]
This is normal, the C backend does not keep the application alive even if threads have been spawned, while the Java backend uses the default Java thread behaviour that keeps the VM alive until the threads finished. 
Adding a delay
```
time.nano.sleep (time.durations.ms 1)
```
after the spawn fixes this for the C backend.

**Comment by michaellilltokiwa** [comment]
@fridis I see. Makes sense. `thread.spawn` returns unit right now. Maybe we should rather return some kind of reference to thread that was being created?
