### ISSUE TITLE
field name reuse should check if exactly same type

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#3072]
When reusing a name for a field I think it would probably be good to enforce that it has the same type.

This currently works but should IMHO produce an error.
```
ex is

  x := "String"
  x := 3

  say x
```

**Comment by fridis** [comment]
This is intentional, I am thinking of cases like this
```
  speed i64 := ds / dt
  check
    speed >= 0 
  speed := speed.as_u64
```
or
```
  data := get_json_string
  data := parse data
```

**Comment by fridis** [comment]
BTW, my example probably does not work, I think `fz` currently treats 
```
  speed i64 := ds / dt
  speed := speed.as_u64
```
and
```
  speed := ds / dt
  speed := speed.as_u64
```
differently, which is probably not a good idea.

**Comment by michaellilltokiwa** [comment]
> This is intentional, I am thinking of cases like this
> 
> ```
>   speed i64 := ds / dt
>   check
>     speed >= 0 
>   speed := speed.as_u64
> ```
> 
> or
> 
> ```
>   data := get_json_string
>   data := parse data
> ```

Okay, seems reasonable.
