### ISSUE TITLE
No errors are raised for abstract feature with unmet constraint

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#309]
Example:
```
ex is
  a is
  b (Set a) is abstract
```
Even though Set has type constraint `hasEquals` and `a` does not implement `hasEquals` there is no error raised when trying to compile the example.

**Comment by fridis** [comment]
I think the problem is in your code, the parameter to `b` is named `Set` and of type `a` :-)

**Comment by fridis** [comment]
But the bug report is still correct, this example reproduces the problem:
```
ex is
  a is
  b (q Set a) is abstract
```

**Comment by michaellilltokiwa** [comment]
@fridis: yes what I wanted to write is this (using <>):
```
ex is
  a is
  b Set<a> is abstract
```
