### ISSUE TITLE
autogenerate choice-call features

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#3123]
for every choice we could automatically generate a feature like this:
```
public option(T type, o option T) => o
```

**Comment by fridis** [comment]
I prefer using `id` for this purpose, e.g., 

    a_or_b : choice a b is
    o1 := id a_or_b a
    o2 := id a_or_b b

and adding convenience features manually if they avoid typing as in 

    o1 := id (option i32) 42

vs

    o1 := option 42
