### ISSUE TITLE
> This looks terribly complicated to me, especially in the case of `for` loops and similar. Is there any motivation behind this change?

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#3124]
> This looks terribly complicated to me, especially in the case of `for` loops and similar. Is there any motivation behind this change?

The motivation is that ignoring a result accidentally is usually a bug that indicates that error handling code is missing or dead code was written. Of course, the APIs and expressions like loops should be designed in a way that this does not create code bloat, e.g. instead of having a mutable map with `put` that returns the old value
```
  _ := m.put k v1
  old_v := m.put k v2
  _ := m.put k v3
```
we should better have two APIs calls, e.g., 
```
  m.put k v1
  old_v := m.replace k v2
  m.put k v3
```

_Originally posted by @fridis in https://github.com/tokiwa-software/fuzion/issues/3094#issuecomment-2129637307_

**Comment by simonvonhackewitz** [comment]
TODO: add `replace` that returns the old value in places where there is a `put` and change the `put` to return nothing.
