### ISSUE TITLE
Idea: add feature for compile-time casts

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#3336]
If we defined 
```
  cast(T type, v T) => v
```
we could use this to force the compiler to perform its casting or tagging magic to a value, e.g., 
```
  l := cast (list u8) nil          
  f := cast f32 0
  b := cast bool TRUE 
  a,b,c is
  abc := if cc then 
      cast (a|b|c) a
    else
      cast (a|b|c) b
  match abc
    a => say "a"
    b => say "b"
    c => say "c"
```
instead of 
```
  l list u8 :=  nil          
  f f32 := 0
  b bool := TRUE 
  a,b,c is
  abc a | b | c := if cc then 
      a
    else
      b
  match abc
    a => say "a"
    b => say "b"
    c => say "c"
```
Are there any cases where this is useful? This could at least be used an example in the tutorial to explain the compiler magic that happens to adapt an expression to match the target type.

**Comment by michaellilltokiwa** [comment]
Turns out we already have a feature with the same signature as `copy`: `id(T type, x T) T => x`

**Comment by michaellilltokiwa** [comment]
@fridis can this be closed?
