### ISSUE TITLE
String helper methods in `dev.flang.util.Errors` should be moved to a different class like `dev.flang.util.StringHelpers`

### ISSUE THREAD

**Issue by simonvonhackewitz** [tokiwa-software/fuzion#3426]
From `src/dev/flang/util/Errors.java` the method `argumentsString(int count)` is used in `src/dev/flang/ast/FeatureName.java` in method `argCountAndIdString()` which is used to generate the paths for the api documentation.

I don't think it is good style to use an error message class methods for something completely different.

**Comment by fridis** [comment]
`Errors.java` contains helpers like `argumentsString` that is used to to create Strings such asl `"no arguments"`, `"obe argument"`,  `"two arguments"`. This should better be moved to a different class like `StringHelpers`.
