### ISSUE TITLE
Question on type syntax

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#360]
```
ex =>
  my_feat(T type, a (T) -> bool,b () -> T) is

  my_feat (Function bool) (x -> true) (() -> (()-> true)) # works
  my_feat<() -> bool> (x -> true) (() -> (()-> true))     # works
  my_feat (() -> bool) (x -> true) (() -> (()-> true))    # does not work
```
I assume the parser parses the first arg in the third example as a lambda. Only later in the frontend it becomes clear that it should really be a type?
Is there a chance to make this work nonetheless?

**Comment by fridis** [comment]
Your interpretation is correct. Originally, actual arguments are parsed as expressions and later, when it is discovered that we need types as actual arguments, they are converted to the corresponding type via a call to `dev.flang.ast.Expr.asType`. For expressions that do not implement `asType`, an error is produced (`Expected actual type parameter in call`). An implementation of `dev.flang.ast.Function.asType` is currently missing resulting in the error.
