### ISSUE TITLE
Optimized `Sequence.find` using Knuth-Morris-Pratt algorithm

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#3711]
Currently, our implementation of `Sequence.find` may end up requiring quadratic runtime. We should use the KMP Algorithm, a racket version is presented [here](https://www.cambridge.org/core/journals/journal-of-functional-programming/article/knuthmorrispratt-illustrated/8EFA77D663D585B68630E372BCE1EBA4). 
A test case that requires quadratic time is `("a"*2*n).find "a"*n+"b"`.

**Comment by michaellilltokiwa** [comment]
Other algorithms that do not have quadratic complexity include Boyer-Moore:
https://stackoverflow.com/questions/56418773/when-is-rabin-karp-more-effective-than-kmp-or-boyer-moore
https://www.cs.utexas.edu/~moore/publications/sustik-moore.pdf

Boyer-Moore seems to offer predictable performance as well.
