### ISSUE TITLE
fzjava: proper support for Java interfaces

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#3835]
When dealing with Java code, there is currently one major problem with the way `fzjava` works. Java interfaces are translated to Fuzion features that fit nowhere in the type hierarchy. As an example, that means that if there is a Java method that takes an parameter implementing the `java.util.Map` interface, and we want to pass a `TreeMap` to this method from Fuzion, we cannot, because Fuzion says that these are incompatible types.

**Comment by michaellilltokiwa** [comment]
related: #3214

**Comment by michaellilltokiwa** [comment]
This can now be done via `fuzion.java.cast`
