### ISSUE TITLE
reorganize the navigation part in the docs

### ISSUE THREAD

**Issue by simonvonhackewitz** [tokiwa-software/fuzion#3837]
What should be in the navigation in the docs (on the left  side) which can be accessed with the hamburger menu?

Also use `AbstractFeature.Kind` instead of `classify()` in `src/dev/flang/tools/docs/Util.java`.

**Comment by michaellilltokiwa** [comment]
All constructors where feature or type is public but the split (Constructors/Types) that is currently shown was a bad idea.
