### ISSUE TITLE
java intrinsics, support for set_field, complement of get_field

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#3852]

**Comment by simonvonhackewitz** [comment]
@michaellilltokiwa Could you explain this in more detail?

**Comment by michaellilltokiwa** [comment]
Sure. We currently have `fuzion.java.get_field0` and `fuzion.java.get_static_field0` instrinsics. We need fuzion.java.set_field0` and `fuzion.java.set_static_field0` to be able to _set_ a field of a java object/class.
