### ISSUE TITLE
Repeated options should result in an error

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#4154]
Try this
```
 > ./build/bin/fz -verbose=10 -verbose=0 -e 'say "hi"' 
hi
```
Would be good if all options that do not make sense repeatedly would result in an error if they are provided repeatedly.

**Comment by simonvonhackewitz** [comment]
I think there is some benefit in allowing this and just keeping the last specified value. Of course it does not make sense to add this option multiple times when typing the command, but there are cases that could result in a command with this option being repeated, e.g.
* setting a bash alias for `fz` with this option but still being able to override it
* if some make target uses it e.g. to run tests, but I want to override it in a single test by modifying the fuzion options variable in that test

**Comment by michaellilltokiwa** [comment]
@simonvonhackewitz 
IMHO especially the second example is a good illustration why repeated options that do not make sense _should_  lead to emitting an error. From fz's perspective we see conflicting/ambiguous settings and I think it is arbitrary to just choose the last option given.
