### ISSUE TITLE
AoC: `container.Mutable_Map` should have `set []` as alternative to `put`

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#4483]
Found this during while working on [Dec 11 Advent of Code part 2](https://github.com/fridis/fuzion_aoc/blob/main/2024/11/part2.fz): Would be nicer to write
```
 cache[k] := res
```
instead of
```
 cache.put k res
```
Same holds for `container.Persistent_Map`.

**Comment by simonvonhackewitz** [comment]
@fridis I think for `container.Persistent_Map` it does not make much sense since it is immutable.

It would look something like this:
`new_cache := (cache[k] := res)`
