### ISSUE TITLE
Poor type inference support for integers in tuples

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#467]
```
num u8 := 1
```
works without problems, as expected the 1 is interpreted as a `u8`.

Likewise,
```
a tuple u8 u8 u8 u8 := tuple 1 2 3 4
```
should interpret the integers on the right hand side as `u8`. However we will get a type error when trying to do this, because the integers are actually interpreted as `i32`.

**Comment by michaellilltokiwa** [comment]
If I just wanted u8 I would probably use an array?
There is also this syntax to init a tuple:
```
a := (u8 1, u8 2, u8 3)
```

But the idea that if one number "in a line" is used as i.e. u8 than all others are u8s as well is worth thinking about. Maybe this just makes things more complicated though, don't know...

**Comment by michaellilltokiwa** [comment]
I see. I think I wasn't fully awake yet when I wrote my comment. :-)

**Comment by fridis** [comment]
Fully agree with Max, but want to point out that the type inference should even go further: 

```
pair(A, B type, l A, r B) : tuple l r
x ref tuple u8 i64 := pair 3 4
```
should create a `pair u8 i64`. I.e., in general, type inference for type parameters should propagate the types through the inheritance chain. 
But not to overload this issue, that should maybe be a separate issue.
