### ISSUE TITLE
Java backend: pass arbitrary arguments to envir.args

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#468]
If we compile a Fuzion program using the C backend, and run the resulting executable, we can then
```bash
./fuzionProgram arg1 arg2 arg3...
```
and access the arguments using the `envir.args` effect.

This does not work with the Java backend, because there is no way of passing arguments to the program.
```bash
fz fuzionProgram.fz arg1 arg2 arg3...
```
returns an error.

If we implement this, we should allow
```bash
fz fuzionProgram.fz -- arg1 arg2 arg3...
```
Note I have used `--` in the example to signify the end of command options, this is customary in other UNIX programs, see <https://unix.stackexchange.com/a/11382> for example.

**Comment by michaellilltokiwa** [comment]
Yes, this is probably how it should be done. There is a comment in the relevant code:
```
NYI: args after cmd name not supported yet
```
Do you want to work on this?

**Comment by fridis** [comment]
> Note I have used `--` in the example to signify the end of command options, this is customary in other UNIX programs, see https://unix.stackexchange.com/a/11382 for example.

Good idea. Nevertheless, check how this is done in other interpreters: Java, Python, Julia, etc. Whatever causes the least confusion by a somewhat experienced developer is my preference
