### ISSUE TITLE
f64: ceiling function broken?

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#469]
Quoting the definition of the ceiling function from Wikipedia:
> the *ceiling function* maps x to the least integer greater than or equal to x, denoted ceil(x) or ⌈x⌉.
This is the generally accepted mathematical definition of the ceiling function.

With Fuzion, the following happens:
```
ex is
  a f64 := 1.0
  say a
  say a.ceil
```
prints
```
1.0
2.0
```

In contrast, in Rust this works as expected:
```rust
fn main() {
    let x = f64::from(1);
    println!("{} {}", x, x.ceil())
}
```
prints
```
1 1
```

**Comment by michaellilltokiwa** [comment]
Yes, seems broken. :-D

**Comment by michaellilltokiwa** [comment]
It should be easy to fix, though. Have look at `float.fz`
