### ISSUE TITLE
tests fail if the NAME shell variable is set 

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#473]
I export my name into the `$NAME` shell variable. This causes all tests to fail when running `make run_tests` because the shell variable takes precedence over e.g. this: <https://github.com/tokiwa-software/fuzion/blob/main/tests/floating_point_math/Makefile#L26>.

**Comment by fridis** [comment]
Please replace `NAME` by something like `FUZION_TEST_NAME`, check for other shell variables used in the Makefiles and scripts and do the same. Try to be consistent in the naming with existing variables.
