### ISSUE TITLE
lib/string: move isAsciiWhiteSpace to strings

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#474]
See tokiwa-software/fuzion-idioms#31 for motivation. The feature should be accessible as `strings.isAsciiWhiteSpace` (in this case, it does not need to be marked `private`).

**Comment by michaellilltokiwa** [comment]
Agree that we should move it but the argument is a `u8` so I'm not sure if strings is the best place. Maybe something like `codepoints.bytes`?

**Comment by michaellilltokiwa** [comment]
Maybe this can be a type feature?
Then it should be possible to this:
```
n := u8 4
n.isAsciiWhiteSpace
```
Might be convenient...
