### ISSUE TITLE
unsigned integers: bitwise NOT

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#475]
Perhaps I missed it, but it seems there is no bitwise NOT for unsigned integers. It's easy to add
```
not (n u64) u64 is
  n ^ u64s.max
```
but maybe something like the `~` prefix in C can be added.

**Comment by michaellilltokiwa** [comment]
I think you are right, it is missing. Would be nice to implement this in a generic way if feasible.
