### ISSUE TITLE
lib: replace infix == with infix =

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#498]
In particular the integers still define the `==` infix as intrinsic and then just make the `=` infix use `==`. Since `=` is preferred now, make `=` the new intrinsic and remove `==`.

**Comment by michaellilltokiwa** [comment]
the idioms, benchmarks, flang.dev-content, may also need to changed.

**Comment by fridis** [comment]
There seems to be bugs in the implementation of ==, eg in String looks like an endless recursion
```
 redef infix == (a, b String) => a == b
```
Maybe we can put a constraint `equatable` on `Monoid.T` and then give an implementation of `infix ==` in Monoid. Then, if this might be needed, we could add a parent to like `GenericMonoid` that does not have this constraint on `T`, but I am not sure if this would be needed at all.
