### ISSUE TITLE
"static" features that do not operate on an instance of an outer feature

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#500]
Make it possible to do something similar to static methods in other languages so that instead of using
```
a f64 := 0
say a.sqrt 9
```
we can do
```
say f64.sqrt 9
```

By itself, this is boring because we can already do
```
say f64s.sqrt 9
```

However, this would be good to have when working with generic types, so that we can do
```
say T.sqrt 9
```
where `T` is some float, but we do not know if it is a `f64` or `f32`.

**Comment by michaellilltokiwa** [comment]
Is think this achieves he same as the planned type instances?
https://flang.dev/design/type_instances
