### ISSUE TITLE
`if` statement does not work as expected when a branch returning `unit` type is not explicitly provided

### ISSUE THREAD

**Issue by WaelYoussfi** [tokiwa-software/fuzion#536]
The following code should reproduce the problem:
```
ex =>
  log(a bool) outcome unit is
    if !a
       error "a is false"

  say (log (envir.args.count < 2))
```

When `a` is a constant, both the C backend and the interpreter return an error at compile time but in the aforementioned case it results in a segmentation fault in C be and NullPointerException in the interpreter be.

**Comment by michaellilltokiwa** [comment]
I can confirm the error in the c-backend but in interpreter the example works for me:
```
--error: a is false--
```
