### ISSUE TITLE
fileio intrinsics use names that may not be nul-terminated but used as C strings in C backend 

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#570]
The C backend contains code like `A0.castTo("char *")` where `A0` is `path.utf8.asArray`, which is not `nul`-terminated. 
Instead, the fuzion code should pass `fuzion.sys.cstring path`, which is `nul`-terminated. Then, the interpreter backend should create a Java string from this using `utf8ByteArrayDataToString`.

**Comment by WaelYoussfi** [comment]
All fileio intrinsics use `utf8.asArray`. I will path that in a separate PR.
