### ISSUE TITLE
shell scripts: improve code quality

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#583]
Our build and test infrastructure relies heavily on shell scripts. We should improve the quality of these shell scripts. A good tool to get some help for that is to use [ShellCheck](https://www.shellcheck.net/). Since this is probably not a high priority issue though, we can do this incrementally, i.e. if we need to change a script, we improve it.

**Comment by michaellilltokiwa** [comment]
to add to this: We could fix all issues that `make shellcheck` currently prints. Then run this target in the CI as well.

**Comment by michaellilltokiwa** [comment]
fixed, shell check is being run as part of CI now.
