### ISSUE TITLE
envir.vars effect enhancements

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#609]
The `envir.vars` effect should provide features to:

- [ ] get all environment variables and their values as a key-value map.
- [x] set an environment variable.
- [x] unset an environment varable.
- [ ] Go also provides `Clearenv` to unset all environment variables, but I am not sure if we should implement that. If someone *really* wants that, they could iterate over the map provided by the first feature and use the third feature to unset each variable.

**Comment by michaellilltokiwa** [comment]
I think this is fine for now. We can open new issue when we see the need for e.g. a map of env-vars.
