### ISSUE TITLE
fzjava and Make should fail with $?=1 for non existing Java module (was: rm: das Entfernen von './build/modules/java.xml/Java_pkg.fz' ist nicht möglich: Datei oder Verzeichnis nicht gefunden)

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#61]
> rm: das Entfernen von './build/modules/java.xml/Java_pkg.fz' ist nicht möglich: Datei oder Verzeichnis nicht gefunden

Happens when running make. Probably because of a different java version (17).

**Comment by michaellilltokiwa** [comment]
see also: #62 for possible fix

**Comment by fridis** [comment]
closing this, it is IMHO ok to require a JDK with graphics for now.
