### ISSUE TITLE
base library: provide networking operations

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#612]
This probably depends on having designed a proper abstraction for read and write as that can then be used with sockets as well. At the beginning, implementing support for TCP sockets should be the priority as that is the most useful thing I suspect (in particular, we can then work on implementing a webserver in Fuzion without loading some Java modules). Later add UDP, Unix sockets, and raw IP sockets.

**Comment by michaellilltokiwa** [comment]
see also #158

**Comment by michaellilltokiwa** [comment]
> One example I often raise to illustrate the design ideals of Plan 9 is to compare its approach to network programming with that of the Unix standard, Berkeley sockets. BSD sockets fly in the face of Unix sensibilities and are quite alien on the system, though by now everyone has developed stockholm syndrome with respect to them so they don’t notice. When everything is supposed to be a file on Unix, why is it that the networking API is entirely implemented with special-purpose syscalls and ioctls? On Unix, creating a TCP connection involves calling the “socket” syscall to create a magic file descriptor, then the “connect” syscall to establish a connection. Plan 9 is much more Unix in its approach: you open /net/tcp/clone to reserve a connection, and read the connection ID from it. Then you open /net/tcp/n/ctl and write “connect 127.0.0.1!80” to it, where “n” is that connection ID. Now you can open /net/tcp/n/data and that file is a full-duplex stream. No magic syscalls, and you can trivially implement it in a shell script.

source: https://drewdevault.com/2022/11/12/In-praise-of-Plan-9.html
