### ISSUE TITLE
cannot define a feature called set

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#627]
```
ex is
  set(a string) unit is
    say "hello $a"
```
in retrospect obvious because `set` is a keyword, but since that is supposedly deprecated I did not expect this to produce an error.

**Comment by michaellilltokiwa** [comment]
I don't see a way to support keywords as feature names? What is your suggestion here? Can you clarify the goal of this issue?

**Comment by michaellilltokiwa** [comment]
Okay, makes sense then.
