### ISSUE TITLE
stream: forAll vs ∀

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#678]
```
# apply f to all elements in this stream
#
redef forAll(f T -> unit) unit is while hasNext do f(next)
```
is not the same as
```
# check if predicate f holds for all elements produced by this stream
#
redef infix ∀ (f T -> bool) bool is
  while hasNext: f next   # hasNext implies f next
  until !hasNext
```
but the name kind of suggests that. Perhaps the first feature could be named something like `run_for_all`, `apply_to_all`, …

**Comment by michaellilltokiwa** [comment]
Good to know that I'm not the only one who got confused by this... Another suggestion. `for_all_do`

**Comment by michaellilltokiwa** [comment]
It's is clear to me too.
`for all` sound very mathy - is mathy a word? :-) - whereas `for each` sounds like `for each loop` and I think of programming...

I think we have a winner.
