### ISSUE TITLE
list: remove forceHead?

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#679]
since `head` returns an `option A`, this is more or less equivalent to calling `head.get`

**Comment by michaellilltokiwa** [comment]
I vote in favor of removing `forceHead`. But we should also think making it more obvious that `get` is actually "dangerous".
Maybe remove `get` as well and add a `postfix !` to option. This would be similar / same? as in Rust then.

**Comment by WaelYoussfi** [comment]
I think it would make sense if `panic` is only permissible under certain operations that are a part of an effect. In that case the user will be well aware that the application is susceptible to crashes.

**Comment by fridis** [comment]
`forceHead`  is redundant with `head.get` and does not incur more typing, so it should probably go.

The `panic` question is difficult, I would like to see as little use of `panic` as possible, but sometimes you just know that a certain branch cannot be executed. We should try to collect such cases and try to identify patterns and find solutions. 

One approach might be a better way to integrate preconditions: The precondition of 'forceHead' already implies that `panic` will not be executed, so can we avoid this somehow? Eventually, I would like implement preconditions as an implicit way to `panic`, ie., 

```
  forceHead
    pre
      debug: !isEmpty
    => (list.this ? nil    => fuzion.std.panic "list.forceHead called on empty list"
                  | c Cons => c.head)
```
should be equivalent to
```
  forceHead =>
    if debug: !isEmpty
      panic "*** some useful message ***"
    else 
      (list.this ? nil    => panic "list.forceHead called on empty list"
                  | c Cons => c.head)
```
but then the ugly redundant `panic` calls are very obvious...
