### ISSUE TITLE
lib: introduce a unit monoid?

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#686]
Should we introduce this unit monoid:
```
unit_monoid : Monoid unit is
  redef infix ∙ (a, b unit) unit is unit
  redef infix == (a, b unit) bool is true
  redef e unit is unit
```
This would for example allow to define the stream/list forAll feature in a functional way:
```
(a.map f).fold unit_monoid
```

**Comment by michaellilltokiwa** [comment]
Personally I think I would use recursion to implement `forAll` in a functional way.

**Comment by fridis** [comment]
I think we should provide a `unit_monoid`. The best place where this should eventually go is `unit.type.monoid`, declared in file `unit.fz`.
