### ISSUE TITLE
list.flatMap is broken

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#733]
```
ex_fromarray is
  m := (marrays Object).new 1000 ""
  s := strings.fromArray m
  say (s + "hello world")
```
returns
```

```
not
```
hello world
```

It works if you change 1000 to 0. I would have expected it to just pre-reserve an array of length given. It seems it does not work this way.

**Comment by michaellilltokiwa** [comment]
only for empty strings it seems to be broken. 
```
sam@debian ~ $ cat ~/playground/test2.fz
ex_fromarray is
  m := (marrays string).new 10 ""
  say m
  m := (marrays string).new 10 "a"
  say m
  m := (marrays i32).new 10 1
  say m

sam@debian ~ $ fz ~/playground/test2.fz 
[]
[a,a,a,a,a,a,a,a,a]
[1,1,1,1,1,1,1,1,1]
```

**Comment by michaellilltokiwa** [comment]
@maxteufel I just realized that as well. Unfortunately removing the special handling breaks quite a few tests. I will look into why that is the case...

**Comment by michaellilltokiwa** [comment]
Hmm, so there seem to be at least two issues then.

**Comment by michaellilltokiwa** [comment]
ugh, probably my mistake...
this should fix it:
```diff
diff --git a/lib/list.fz b/lib/list.fz
index 455b41da..4b823dc1 100644
--- a/lib/list.fz
+++ b/lib/list.fz
@@ -163,7 +163,7 @@ list(A type) : choice nil (Cons A (list A)), Sequence A is
       _ nil  => nil
       c Cons =>
         match (f c.head).asList
-          _ nil => nil
+          _ nil => c.tail.flatMap B f
           c2 Cons =>
             ref : Cons B (list B)
             // Cons B (list B) with    # NYI: better syntax for anonymous feature

```

**Comment by michaellilltokiwa** [comment]
Maybe it is time to add tests for every std-lib feature we add but in this case I'm not sure if I would have written a test that would have caught this error...

**Comment by michaellilltokiwa** [comment]
@maxteufel do you want to submit a PR or should I?

**Comment by michaellilltokiwa** [comment]
@maxteufel It does not fix the original issue in my tests?

**Comment by michaellilltokiwa** [comment]
@maxteufel You are right. I got confused... I was thinking of the following but you already opened another issue for that:
```
ex_fromarray is
  m := (marrays Object).new 10 ""
  say m
```
