### ISSUE TITLE
special treatment of empty strings in strings.concat to be reconsidered

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#744]
The `strings.concat` monoid treats empty strings specially, see <https://github.com/tokiwa-software/fuzion/blob/main/lib/string.fz#L539>.

This displays a list of empty strings like an empty list rather than `[,,,]` which is confusing.

See also: <https://github.com/tokiwa-software/fuzion/issues/733#issuecomment-1340675163>

**Comment by fridis** [comment]
Here is a small example
```
 > echo 'say ["",""].as_list' | ./build/bin/fz -
[]
 > echo 'say ["a","a"].as_list' | ./build/bin/fz -
[a,a]
```
@maxteufel , can you fix this?
