### ISSUE TITLE
`...` syntax and open generics

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#768]
from `lib/Function.fz`:

```
Function(R type, A type...) ref is
  call(a A) R is abstract
```

It is a bit confusing that we have `A type...` but no `...` in `call(a A)`. It might be good to require some kind of `...`-syntax in the latter as well, you can easily miss this if there were 100 lines of code between the first and second line of the example.

**Comment by fridis** [comment]
I think this makes sense, had the same thought a long time ago. I see two possibilities
```
  call(a A...) R is abstract
```
or
```
  call(a... A) R is abstract
```
I think I prefer the former. 
So we would need to extend the grammar for actuals to allow `...` after the type and later, maybe during `resolveTypes`, we should check that these dots are present for types that are open generics.
