### ISSUE TITLE
Uninitialized field is not detected

### ISSUE THREAD

**Issue by fridis** [tokiwa-software/fuzion#83]
This small example
```
> cat test.fz
test is
  a, b, c i32 := ?
  set a := b
  say a
  say b
  say c
```
accesses uninitialized data:
```
 > ./build/bin/fz test
-555555555
-555555555
-555555555
```
This bug also causes tests/forwardref_negative to fail.

**Comment by michaellilltokiwa** [comment]
#260 possibly related

**Comment by michaellilltokiwa** [comment]
Declaring uninitialized fields like this is disallowed since 6f70e556. Closing.
