### ISSUE TITLE
field has unexpected value in C backend

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#851]
Insert the following at this line: <https://github.com/tokiwa-software/fuzion/blob/44a9aa8591cc0cc5db486644bafee4e7a45b6f06/lib/io/file/read.fz#L33>

```
  private bufsize u64 := 12

  say_bufsize unit is
    say bufsize
```

now use the following example:

```
ex_buf is
  io.file.read.say_bufsize
```

this will print 12 using the Java backend, as expected. Using the C backend, it will print 0.

If you change the field to be a constant feature, then this will work as expected using both the C and Java backends.

**Comment by michaellilltokiwa** [comment]
I can not reproduce this, (anymore).
