### ISSUE TITLE
incompatible type parameter when attempting to define type.equality

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#881]
In `lib/comparable_sequence.fz`, this change:

```diff
@@ -42,11 +42,10 @@ is
     else
       (0..(from.count - 1)) ∀ (i -> fa[i] = oa[i])
 
-  # NYI: #637:
-  # comparable_sequence(A type : hasEquals A, a, b comparable_sequence A) bool is
-  #   aa := a.asArray
-  #   ba := b.asArray
-  #   if aa.count ≟ ba.count
-  #     (0..(a.count - 1)) ∀ (i -> equals A aa[i] ba[i])
-  #   else
-  #     false
+  fixed type.equality(a, b comparable_sequence A) bool is
+    aa := a.asArray
+    ba := b.asArray
+    if aa.count ≟ ba.count
+      (0..(a.count - 1)) ∀ (i -> equals A aa[i] ba[i])
+    else
+      false
```

causes the following error:

```
./build/lib/comparable_sequence.fz:49:34: error 1: Incompatible type parameter
      (0..(a.count - 1)) ∀ (i -> equals A aa[i] ba[i])
---------------------------------^
formal type parameter 'T' with constraint 'has_equality'
actual type parameter 'comparable_sequence.type.A'

one error.
```

**Comment by fridis** [comment]
This is clear, the constraint on `comparable_sequence.A` is `hasEquals` and not `has_equality`, and this constraint is also used for `comparable_sequence.type.A`. We could, however, improve the error message to include the source code position of  the declaration of `comparable_sequence.A` and to maybe not talk about the artificial `comparable_sequence.type.A` at all, but only about `comparable_sequence.A`.

**Comment by fridis** [comment]
@maxteufel: Since we cannot put two type constraints on a type parameter, you could make `hasEquals` inherit from `has_equality` for now.  This should avoid this error.
