### ISSUE TITLE
unsafe features and the C backend

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#934]
Currently, "unsafe features" need to be enabled manually in the interpreter, while the C backend does not care. This currently causes some errors in the idioms/flang.dev `check_examples_c` target. Do we want to change this or will "unsafe features" disappear when the interpreter does?

**Comment by fridis** [comment]
The only reason for this is as one small barrier against attacks via running malicious code in `flang.dev`. The default for unsafe features should be enabled (after the scripts on flang.dev where changed to all disable these).

**Comment by michaellilltokiwa** [comment]
@maxteufel  can this be closed?
