### ISSUE TITLE
type parameter constraints in inner features

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#967]
It might make sense to move features such as `Sequences.find` to to `Sequence`. This does not work at the moment because they operate on a type parameter more constrained than the outer feature does. Could we make the following work?

```
find(constrain T type : hasEquals T, x Sequence T) => (searchable_sequence T Sequence.this).index_of x
```

In cases where T does not fulfill the constraint, the find feature simply would not exist/return a type error.

**Comment by fridis** [comment]
The main question is where to add this syntax sugar. The precondition might be a nice place, i.e., 

    find(x Sequence T)
      pre
        T : hasEquals T
    => 
      (searchable_sequence T Sequence.this).index_of x

We could implement this by adding an Intrinsic to `Type.fz`

    # does this type inherit from parent P?
    infix : (P type) bool is instrinsic

This would, however, require an additional rule that forbids  weakening of this precondition in a redefinition.
